// Command mksyscalls generates the syscall name -> number tables used by the
// cgo-free seccomp filter builder.
//
// libseccomp carries a hand-maintained table per architecture. Generating ours
// from the per-architecture constants that golang.org/x/sys/unix derives from
// the kernel headers means the numbers cannot drift from the kernel's own
// numbering, and leaves nothing to maintain by hand.
//
// Not every architecture libseccomp knows about has a table in x/sys/unix:
// s390 (31-bit), the mips n32 ABIs and x32 are missing. The generated tables
// simply do not cover them.
//
// Usage (from libcontainer/seccomp):
//
//	go run ./internal/mksyscalls -o syscalls_linux.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// goarchToSeccomp maps a GOARCH to the architecture name used by OCI seccomp
// profiles, i.e. the names in libcontainer/seccomp/config.go's archs map.
var goarchToSeccomp = []struct{ goarch, seccomp string }{
	{"386", "SCMP_ARCH_X86"},
	{"amd64", "SCMP_ARCH_X86_64"},
	{"arm", "SCMP_ARCH_ARM"},
	{"arm64", "SCMP_ARCH_AARCH64"},
	{"loong64", "SCMP_ARCH_LOONGARCH64"},
	{"mips", "SCMP_ARCH_MIPS"},
	{"mips64", "SCMP_ARCH_MIPS64"},
	{"mips64le", "SCMP_ARCH_MIPSEL64"},
	{"mipsle", "SCMP_ARCH_MIPSEL"},
	{"ppc", "SCMP_ARCH_PPC"},
	{"ppc64", "SCMP_ARCH_PPC64"},
	{"ppc64le", "SCMP_ARCH_PPC64LE"},
	{"riscv64", "SCMP_ARCH_RISCV64"},
	{"s390x", "SCMP_ARCH_S390X"},
}

// entryRe matches one "SYS_FOO = 123" line in x/sys/unix's zsysnum files.
var entryRe = regexp.MustCompile(`^\s*SYS_([A-Z0-9_]+)\s*=\s*(0x[0-9a-fA-F]+|[0-9]+)\s*$`)

// nonSyscalls are constants that live in the same table but are not syscalls.
var nonSyscalls = map[string]bool{
	"syscall_mask": true,
}

func main() {
	out := flag.String("o", "", "output file (default stdout)")
	flag.Parse()

	dir, err := unixPkgDir()
	if err != nil {
		fatal(err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `//go:build linux

// Code generated by internal/mksyscalls. DO NOT EDIT.
//
// The numbers are taken from golang.org/x/sys/unix's per-architecture tables,
// which in turn come from the kernel headers.

package seccomp

// syscallNumbers maps a seccomp architecture to that architecture's
// syscall name -> number table. The architectures are the SCMP_ARCH_* names
// used by OCI seccomp profiles.
var syscallNumbers = map[string]map[string]uint32{
`)

	for _, a := range goarchToSeccomp {
		path := filepath.Join(dir, "zsysnum_linux_"+a.goarch+".go")
		nums, err := parseSysnums(path)
		if err != nil {
			fatal(err)
		}
		if len(nums) == 0 {
			fatal(fmt.Errorf("%s: no syscalls found", path))
		}

		names := make([]string, 0, len(nums))
		for name := range nums {
			names = append(names, name)
		}
		sort.Strings(names)

		fmt.Fprintf(&buf, "\t%q: {\n", a.seccomp)
		for _, name := range names {
			fmt.Fprintf(&buf, "\t\t%q: %d,\n", name, nums[name])
		}
		fmt.Fprintf(&buf, "\t},\n")
	}
	fmt.Fprintf(&buf, "}\n")

	fmt.Fprintf(&buf, `
// goarchToSeccompArch maps runtime.GOARCH to the seccomp architecture name used
// by OCI seccomp profiles.
var goarchToSeccompArch = map[string]string{
`)
	for _, a := range goarchToSeccomp {
		fmt.Fprintf(&buf, "\t%q: %q,\n", a.goarch, a.seccomp)
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fatal(fmt.Errorf("formatting generated source: %w", err))
	}
	if *out == "" {
		os.Stdout.Write(src)
		return
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fatal(err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}

// unixPkgDir locates the golang.org/x/sys/unix source directory. With a vendor
// directory present (runc vendors its dependencies) this resolves to the
// vendored copy.
func unixPkgDir() (string, error) {
	out, err := exec.Command("go", "list", "-f", "{{.Dir}}", "golang.org/x/sys/unix").Output()
	if err != nil {
		return "", fmt.Errorf("locating golang.org/x/sys/unix: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// parseSysnums reads one zsysnum file and returns its syscall names and
// numbers, keyed by the name the kernel uses (lower-cased, without the SYS_
// prefix), which is what OCI seccomp profiles use.
func parseSysnums(path string) (map[string]uint32, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	nums := make(map[string]uint32)
	for _, line := range strings.Split(string(data), "\n") {
		m := entryRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		name := strings.ToLower(m[1])
		if nonSyscalls[name] {
			continue
		}
		n, err := strconv.ParseUint(m[2], 0, 32)
		if err != nil {
			return nil, fmt.Errorf("%s: %q: %w", path, line, err)
		}
		// The ARM private syscalls (0x0f0000+) are not in the libseccomp
		// tables we are matching either.
		if n > 0xffff {
			continue
		}
		nums[name] = uint32(n)
	}
	return nums, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "mksyscalls:", err)
	os.Exit(1)
}
